<?php

namespace Affiliateforge\PhpAdmitadApi\Api\Endpoints\PublisherReports;

use Affiliateforge\PhpAdmitadApi\Api\CommandDTO;
use Affiliateforge\PhpAdmitadApi\Api\ResponseDTO;
use Affiliateforge\PhpAdmitadApi\Api\Traits\HttpMethods\GET;
use Psr\Http\Message\ResponseInterface;

class GetReportsByActions extends CommandDTO
{
    use GET;

    public function getUrlPath(): string
    {
        return '/statistics/actions/';
    }

    public function getQueryParams(): array
    {
        return parent::getQueryParams(); // TODO: Change the autogenerated stub
    }

    public function makeResponseDTO(ResponseInterface $response): GetReportsByActionsResponse
    {
        return new GetReportsByActionsResponse($response);
    }
}